### ISSUE TITLE
Adobe Digital Editions 4.0

### ISSUE THREAD

**Issue by alexandre-mbm** [alexandre-mbm/arch-pkgs#2]
- [x] criar empacotamento
- [ ] testar: mover backup de `~/.wine`
- [x] instruir no [WineHQ](https://appdb.winehq.org/objectManager.php?sClass=version&iId=30928)
- [x] ~~divulgar no [Fórum do Clube do Hardware](http://forum.clubedohardware.com.br/topic/1110559-wine-deveria-executar-adobe-digital-editions-40/?p=6102503)~~

---

**TODO** adobe-digital-editions/adobe-digital-editions.install f15424ed1516e67c4a963e5afe2d65836eb8aad4
- [x] 7: stop for capture user's answer
- [ ] 12: discover
- [x] 40: ~~msg2 etc.~~  
- [x] 41: users with ~/.wine — **an automated uninstall method is need**

**Comment by alexandre-mbm** [comment]
Log do desinstalador:

```
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\DigitalEditions.exe
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\ADEAutoUpdater_403.exe
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\rmsdk_wrapper.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\log4net.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\uninstall.exe
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\userStyle.css
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\host_app_feedback.js
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\reader.html
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\ReadiumJS_InputFiles.txt
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\load.html
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\host_app_reference_files\sample_styles.css
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\host_app_reference_files\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\Readium.js
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\AdobeRDMHelper.js
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\lib\mathjax\MathJax.js
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\lib\mathjax\
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\lib\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\rmsdk_epubReadingSystem.js
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\README.md
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\static\sdk.css
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\static\MOHighlight.css
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\static\annotations.css
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\static\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\contentframe\load.js
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\contentframe\
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\readium-shared-js\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\ReaderClientCert.sig
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\MinionPro-Regular.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\MyriadPro-BoldIt.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\CourierStd-Oblique.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\CourierStd-Bold.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\CourierStd.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\MyriadPro-Bold.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\MinionPro-Bold.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\MyriadPro-It.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\MinionPro-BoldIt.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\MyriadPro-Regular.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\MinionPro-It.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\CourierStd-BoldOblique.otf
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\SymbolStd.otf
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\fonts\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\hyphenDicts\hyph_pt.dic
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\hyphenDicts\hyph_en.dic
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\hyphenDicts\hyph_es.dic
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\hyphenDicts\hyph_de.dic
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\hyphenDicts\hyph_fr.dic
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\hyphenDicts\hyph_it.dic
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\hyphenDicts\
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\resources\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\de\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\de\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\de\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\es\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\es\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\es\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\fr\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\fr\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\fr\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\it\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\it\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\it\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\ja\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\ja\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\ja\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\ko\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\ko\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\ko\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\nl\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\nl\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\nl\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\pt\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\pt\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\pt\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\zh-Hans\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\zh-Hans\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\zh-Hans\.\
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\zh-Hant\.\migration.resources.dll
Excluindo arquivo: C:\Program Files\Adobe\Adobe Digital Editions 4.0\zh-Hant\.\DigitalEditions.resources.dll
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\zh-Hant\.\
Excluindo arquivo: C:\users\Public\Start Menu\Programs\Adobe\Adobe Digital Editions 4.0\Home Page.lnk
Excluindo arquivo: C:\users\Public\Start Menu\Programs\Adobe\Adobe Digital Editions 4.0\Uninstall.lnk
Excluindo arquivo: C:\users\Public\Start Menu\Programs\Adobe\Adobe Digital Editions 4.0\Adobe Digital Editions 4.0.lnk
Excluindo arquivo: C:\users\Public\Start Menu\Programs\Adobe\Adobe Digital Editions 4.0\Help.lnk
Excluindo arquivo: C:\users\Public\Start Menu\Programs\Adobe Digital Editions 4.0.lnk
Excluindo arquivo: C:\users\Public\Área de Trabalho\Adobe Digital Editions 4.0.lnk
Excluindo pasta: C:\users\Public\Start Menu\Programs\Adobe\Adobe Digital Editions 4.0\
Excluindo pasta: C:\Program Files\Adobe\Adobe Digital Editions 4.0\
Excluindo arquivo: C:\users\alexandre\Meus Documentos\My Digital Editions\welcome.epub
Excluindo arquivo: C:\users\alexandre\Meus Documentos\My Digital Editions\Manifest\welcome.epub.xml
Excluindo arquivo: C:\users\alexandre\Meus Documentos\My Digital Editions\Annotations\welcome.epub.annot
Excluindo arquivo: C:\users\alexandre\Meus Documentos\My Digital Editions\Thumbnails\welcome.epub.png
Concluído
```

**Comment by alexandre-mbm** [comment]
Console durante uma instalação bem sucedida:

``` console
$ yaourt -S adobe-digital-editions

==> Fazendo download do PKGBUILD de adobe-digital-editions do AUR...
x .SRCINFO
x adobe-digital-editions.install
x PKGBUILD
Comment by dschein  (2015-05-27 19:27)
== Validating source files with md5sums...
ADE_4.0_Installer.exe ... FAILED
== ERROR: One or more files did not pass the validity check!

I don't actually see the md5 sums on Adobe's download page.  Did you add that detail and then they subsequently tweaked the download without a version change?

Comment by evilgnome  (2015-07-24 15:26)
If this works for someone, please go ahead and push it to AUR 4.

For me, after install, running with wine results in:

fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
The entry point method could not be loaded

Comment by alexandre-mbm  (2015-07-26 03:02)
I fixed and migrated the package to AUR 4. New site: https://aur4.archlinux.org/packages/adobe-digital-editions/

Comment by alexandre-mbm  (2015-07-26 08:37)
Install instructions in Portuguese of Brazil: https://github.com/alexandre-mbm/arch-pkgs/wiki/adobe-digital-editions

adobe-digital-editions 4.0.3-3  (Ter Mar 31 04:53:11 BRT 2015)
( Pacote sem suporte: Potencialmente perigoso ! )
==> Editar PKGBUILD ? [S/n] ("A" para abortar)
==> ------------------------------------------
==> n

==> Dependências de adobe-digital-editions:
 - wine (já instalado)
 - samba (já instalado)
 - dex (já instalado)
 - wine (já instalado)
 - winetricks (já instalado)


==> Editar adobe-digital-editions.install ? [S/n] ("A" para abortar)
==> ----------------------------------------------------------------
==> n

==> Continuar a compilação de adobe-digital-editions ? [S/n]
==> --------------------------------------------------------
==> 
==> Compilando e instalando pacote
==> Criando o pacote: adobe-digital-editions 4.0.3-3 (Dom Jul 26 06:16:06 BRT 2015)
==> Verificando as dependências de tempo de execução...
==> Verificando as dependências de tempo de compilação...
==> Obtendo fontes...
  -> Baixando ADE_4.0_Installer.exe...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8268k  100 8268k    0     0  1203k      0  0:00:06  0:00:06 --:--:-- 1214k
==> Validando arquivos fonte com md5sums...
    ADE_4.0_Installer.exe ... Ignorada
==> Extraindo fontes...
==> Entrando no ambiente fakeroot...
==> Iniciando package()...
==> Organizando a instalação...
  -> Expurgando arquivos indesejados...
  -> Removendo arquivos libtool...
  -> Removendo arquivos de biblioteca estática...
  -> Comprimindo páginas de man e info...
  -> Removendo símbolos desnecessários dos executáveis e bibliotecas...
==> Criando pacote "adobe-digital-editions"...
  -> Gerando arquivo .PKGINFO...
  -> Adicionando o arquivo install...
  -> Gerando arquivo .MTREE ...
  -> Compactando pacote...
==> Saindo do ambiente de fakeroot.
==> Compilação concluída: adobe-digital-editions 4.0.3-3 (Dom Jul 26 06:16:19 BRT 2015)

==> Continuar a instalação de adobe-digital-editions ? [S/n]
==> [V]er conteúdo do pacote [C]hecar pacote com namcap
==> ---------------------------------------------------
==> s

[sudo] senha para alexandre: 
carregando pacotes...
resolvendo dependências...
procurando por pacotes conflitantes...

Pacotes (1) adobe-digital-editions-4.0.3-3

Tamanho total instalado:  8,08 MiB

:: Continuar a instalação? [S/n] s
(1/1) verificando chaves no chaveiro                                        [###########################################] 100%
(1/1) verificando integridade do pacote                                     [###########################################] 100%
(1/1) carregando arquivos do pacote                                         [###########################################] 100%
(1/1) verificando conflitos de arquivo                                      [###########################################] 100%
(1/1) verificando espaço em disco disponível                                [###########################################] 100%
(1/1) instalando adobe-digital-editions                                     [###########################################] 100%
atenção: permissões de diretório diferem em /tmp/
sistema de arquivos: 1777  pacote: 755
Install procedure

Users possessing HOME: alberto alexandre
Who are you? 
alexandre

OK, alexandre! Continuing...

Executing w_do_call corefonts
corefonts already installed, skipping
Executing w_do_call dotnet40
dotnet40 already installed, skipping
Executing w_do_call msxml3
msxml3 already installed, skipping
err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
fixme:shell:SHAutoComplete stub
fixme:exec:SHELL_execute flags ignored: 0x00000100
fixme:thread:SetThreadStackGuarantee (0x33fbd4): stub
err:ole:CoGetContextToken apartment not initialised
fixme:shell:URL_ParseUrl failed to parse L"PresentationFramework"
fixme:shell:URL_ParseUrl failed to parse L"WindowsBase"
fixme:shell:URL_ParseUrl failed to parse L"System.Xaml"
fixme:shell:URL_ParseUrl failed to parse L"PresentationCore"
fixme:shell:URL_ParseUrl failed to parse L"System"
fixme:advapi:RegisterTraceGuidsW (0x550b9c5c, 0x5516e048, {e13b77a8-14b6-11de-8069-001b212b5009}, 1, 0x33b90c, (null), (null), 0x5516e048): stub
fixme:advapi:LsaOpenPolicy ((null),0x33e44c,0x00000800,0x33e424) stub
fixme:advapi:LsaClose (0xcafe) stub
fixme:nls:GetUserPreferredUILanguages stub: 0 0x33d8a4 (nil) 0x33d8a0
fixme:thread:GetThreadPreferredUILanguages 0, 0x33d8a4, (nil) 0x33d8a0
fixme:shell:URL_ParseUrl failed to parse L"UIAutomationTypes"
fixme:advapi:RegisterTraceGuidsW (0xd2081a, (nil), {e13b77a8-14b6-11de-8069-001b212b5009}, 1, 0x33e590, (null), (null), 0x33e598): stub
fixme:shell:URL_ParseUrl failed to parse L"System.Core"
fixme:advapi:RegisterTraceGuidsW (0xd20be2, (nil), {8e9f5090-2d75-4d03-8a81-e5afbf85daf1}, 1, 0x4cfb89c, (null), (null), 0x108da54): stub
fixme:shell:URL_ParseUrl failed to parse L"mscorlib.resources"
fixme:shell:URL_ParseUrl failed to parse L"DigitalEditions.resources"
fixme:shell:URL_ParseUrl failed to parse L"mscorlib.resources"
fixme:shell:URL_ParseUrl failed to parse L"DigitalEditions.resources"
fixme:msg:ChangeWindowMessageFilter c05d 00000001
fixme:advapi:RegisterTraceGuidsW (0x56216bfc, 0x56263028, {0635afbf-f587-4fe5-a020-edca759acbd9}, 1, 0x33da98, (null), (null), 0x56263028): stub
err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
fixme:driver:GdiEntry13 stub
fixme:d3d:check_fbo_compat Format WINED3DFMT_R16G16_UNORM with rendertarget flag is not supported as FBO color attachment, and no fallback specified.
fixme:d3d:check_fbo_compat Format WINED3DFMT_R16G16B16A16_UNORM with rendertarget flag is not supported as FBO color attachment, and no fallback specified.
fixme:win:EnumDisplayDevicesW ((null),0,0x538e3d4,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x538e520,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x538e520,0x00000000), stub!
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x1ad5b0, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8X8_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:shell:URL_ParseUrl failed to parse L"PresentationFramework.classic"
fixme:shell:URL_ParseUrl failed to parse L"PresentationFramework.Classic.resources"
fixme:shell:URL_ParseUrl failed to parse L"PresentationFramework.Classic.resources"
fixme:process:FlushProcessWriteBuffers : stub
fixme:shell:URL_ParseUrl failed to parse L"DigitalEditions.resources"
fixme:shell:URL_ParseUrl failed to parse L"PresentationFramework.resources"
fixme:shell:URL_ParseUrl failed to parse L"PresentationFramework.resources"
fixme:shell:URL_ParseUrl failed to parse L"UIAutomationProvider"
fixme:shell:URL_ParseUrl failed to parse L"System.Printing"
fixme:shell:URL_ParseUrl failed to parse L"ReachFramework"
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:advapi:RegisterTraceGuidsW (0x105b0d8c, (nil), {f7b697a3-4db5-4d3b-be71-c4d284e6592f}, 7, 0x10827c30, (null), (null), 0x10a648b8): stub
fixme:process:GetNumaHighestNodeNumber (0x33a874): semi-stub
err:ole:CoGetClassObject class {35440327-1517-4b72-865e-3ffe8e97002f} not registered
err:ole:CoGetClassObject no class object {35440327-1517-4b72-865e-3ffe8e97002f} could be created for context 0x1
fixme:ver:GetCurrentPackageId (0x5c7e9c8 (nil)): stub
fixme:shell:URL_ParseUrl failed to parse L"DigitalEditions.resources"
fixme:shell:URL_ParseUrl failed to parse L"DigitalEditions.resources"
fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for bias 180, std (d/m/y): 0/00/0000, dlt (d/m/y): 0/00/0000
fixme:shell:URL_ParseUrl failed to parse L"System.Configuration"
fixme:shell:URL_ParseUrl failed to parse L"System.Xml"
fixme:shell:URL_ParseUrl failed to parse L"DigitalEditions.resources"
fixme:wtsapi:WTSRegisterSessionNotification Stub 0x2005e 0x00000000
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
fixme:d3d:wined3d_check_device_format_conversion wined3d 0x1ad5b0, adapter_idx 0, device_type WINED3D_DEVICE_TYPE_HAL, src_format WINED3DFMT_B8G8R8X8_UNORM, dst_format WINED3DFMT_B8G8R8X8_UNORM stub!
fixme:d3d:resource_access_from_pool Unhandled pool 0x6.
fixme:d3d_surface:surface_init Unknown pool 0x6.
fixme:d3d:resource_access_from_pool Unhandled pool 0x6.
fixme:d3d:state_lastpixel Last Pixel Drawing Disabled, not handled yet
fixme:shell:URL_ParseUrl failed to parse L"PresentationCore.resources"
fixme:shell:URL_ParseUrl failed to parse L"PresentationCore.resources"
fixme:wer:WerRegisterMemoryBlock (0x56263970 352) stub
fixme:wer:WerRegisterMemoryBlock (0x5626345c 4) stub
fixme:shell:URL_ParseUrl failed to parse L"DigitalEditions.resources"
fixme:d3d9:Direct3DShaderValidatorCreate9 stub
err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
fixme:shell:URL_ParseUrl failed to parse L"System.Web"
err:ole:CoInitializeEx Attempt to change threading model of this apartment from apartment threaded to multi-threaded
fixme:advapi:LsaOpenPolicy ((null),0x33d954,0x00000800,0x33d92c) stub
fixme:advapi:LsaClose (0xcafe) stub
fixme:shell:URL_ParseUrl failed to parse L"PresentationCore.resources"
fixme:shell:URL_ParseUrl failed to parse L"PresentationCore.resources"
err:ole:CoInitializeEx Attempt to change threading model of this apartment from apartment threaded to multi-threaded
fixme:wincodecs:ColorTransform_Initialize ignoring color contexts
fixme:d3d:resource_access_from_pool Unhandled pool 0x6.
fixme:d3d_surface:surface_init Unknown pool 0x6.
fixme:d3d:resource_access_from_pool Unhandled pool 0x6.
fixme:thread:NtQueryInformationThread info class 16 not supported yet
fixme:wtsapi:WTSUnRegisterSessionNotification Stub 0x2005e
err:d3d:context_restore_gl_context Failed to restore GL context 0x91005 on device context 0x10065, last error 0x6.
fixme:advapi:UnregisterTraceGuids 0: stub
```
