### ISSUE TITLE
aliases

### ISSUE THREAD

**Issue by alexandre-mbm** [alexandre-mbm/arch-pkgs#5]
- [x] **pkgsource**: makepkg --source
- [x] **pkgaur**: atualizar banco de dados e tentar instalar/atualizar pacote
- [x] ~~trocar~~ documentação do `README.md` para corresponder ao `aliases`
- [x] declarar licença MIT de `aliases`no `README.md`
- [ ] **corrigir:** `pkgnow` não atualiza com o PKGBUILD; usar _functions_ invés de comandos `alias`
- [ ] mover para projeto de pacote separado
- [ ] criar o empacotamento aqui

---

**TODO** aliases 397d14015815cfe4ce02e1b8579755ba36d92747
- [ ] 32: validações!
- [ ] 34: ~~ampliar para a seguinte possibilidade~~ fazer `../aliases -L` e/ou `../aliases --load`
- [ ] 39:: ~~talvez funcione com PATH...~~ fazer `./aliases DIR` executando `source` em si e saindo
- [ ] 49: usá-lo melhor; receber valor como parâmetro?
- [ ] 69: ~~-h e --help~~ fazer `./aliases` exibindo a ajuda

---
- [x] criar um auxiliar para simplificar `makedepends`; pode ajudar:

Ref.: https://wiki.archlinux.org/index.php/PKGBUILD#makedepends (ver #7)
